version: '3'
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pagarmesupport
  api:
    build: ./argus-github-api
    ports:
      - "8070:8070"
    links:
      - database
    environment:
      - PORT=8070
      - DB_URL=mongodb://database:27017/pagarmesupport
    volumes:
      - ./argus-github-api:/home/node/app
  dashboard:
    build: .
    ports:
      - "3000:3000"
    links:
      - api
    env_file:
      - .env
    environment:
      - API_URL=http://api:8070
    volumes:
      - ./argus:/home/app/pagarme-issues-dashboard/node_modules/@argus-dashboard/components
      - ./argus-github-extension:/home/app/pagarme-issues-dashboard/node_modules/@argus-dashboard/github-extension
      - ./argus-server:/home/app/pagarme-issues-dashboard/node_modules/@argus-dashboard/server
      - ./argus-skin:/home/app/pagarme-issues-dashboard/node_modules/@argus-dashboard/skin
      - ./pagarme-issues-dashboard:/home/app/pagarme-issues-dashboard
